#!/usr/bin/env python3
"""Generate static inventory from the hash-verified JAR without running app code."""
import argparse
import hashlib
import json
from pathlib import Path
import re
import subprocess
import zipfile
from baseline import ROOT, verify_original, tree_hash


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--jdk', type=Path, required=True)
    args = parser.parse_args()
    jar = ROOT / 'original/RAID_Admin_original.jar'
    verify_original(jar)
    out = ROOT / 'audit'
    with zipfile.ZipFile(jar) as z:
        hashes = {n: hashlib.sha256(z.read(n)).hexdigest() for n in z.namelist() if not n.endswith('/')}
        classes = sorted(n[:-6].replace('/', '.') for n in hashes if n.endswith('.class') and n.startswith(('com/apple/', 'com/chaotic/')))
        bytecode = subprocess.check_output([str(args.jdk / 'bin/javap'), '-classpath', str(jar), '-p', '-c', '-constants'] + classes, text=True)
        methods = []; current = None; cls = None
        for line in bytecode.splitlines():
            m = re.match(r'^(?:[\w]+ )*(?:class|interface) ([\w.$]+).*\{$', line)
            if m: cls = m[1]; current = None
            if re.match(r'^  [^ ].*\(.*\).*;$', line) or line == '  static {};':
                current = {'class': cls, 'signature': line.strip(), 'calls': [], 'strings': []}
                methods.append(current)
            if current:
                if '// Method ' in line or '// InterfaceMethod ' in line:
                    current['calls'].append(line.split('// ', 1)[1])
                if '// String ' in line:
                    current['strings'].append(line.split('// String ', 1)[1])
        # Preserve literals only for the request factory and firmware request definitions.
        for m in methods:
            if not m['class'].startswith('com.apple.xsr.net.AcpxMessageFactory') and m['class'] != 'com.apple.xsr.net.UpdateFirmwareRequest':
                del m['strings']
        result = {'scope': 'all com.apple and com.chaotic classes; static presence is not proof of reachability or functionality', 'jar_sha256': hashlib.sha256(jar.read_bytes()).hexdigest(), 'class_count': len(classes), 'classes': classes, 'methods': methods, 'entry_hashes': hashes}
        (out / 'static-inventory.json').write_text(json.dumps(result, indent=2) + '\n')
        factory = [m for m in methods if m['class'] == 'com.apple.xsr.net.AcpxMessageFactory' and re.search(r'\bnew\w+Request\(', m['signature'])]
        protocol = ['# Static controller-operation catalog', '', 'Generated by `tools/inventory.py` from the verified original JAR. All overloads are included. Literals are evidence, not a substitute for request schemas or hardware tests. RPC names beginning `/raid/` or `/system/` are carried inside POST `/cgi-bin/perform`, not separate HTTP endpoints.', '', '| Factory signature | String literals (command, endpoint, parameter names, defaults) |', '|---|---|']
        for m in factory:
            protocol.append('| `' + m['signature'].replace('|', '\\|') + '` | ' + '; '.join('`' + s.replace('|','\\|').replace('`','') + '`' for s in m.get('strings',[])) + ' |')
        (out / 'CONTROLLER-OPERATIONS.md').write_text('\n'.join(protocol) + '\n')
        ui = ['# Static UI and CLI inventory', '', 'Every com.apple.xsr class is listed, including anonymous listeners and non-UI model/transport classes so hidden paths remain visible. The JSON companion records every declared method and call site. This is a complete static class inventory, not a completed behavioral inventory.', '', '## Named actions', '']
        ui += ['- `' + c + '`' for c in classes if c.startswith('com.apple.xsr.') and c.endswith('Action')]
        ui += ['', '## UI-to-request call sites', '', '| Class / method | Factory call |', '|---|---|']
        for m in methods:
            if m['class'].startswith('com.apple.xsr.') and not m['class'].startswith('com.apple.xsr.net.'):
                for call in m['calls']:
                    if 'AcpxMessageFactory.new' in call:
                        ui.append('| `' + m['class'] + ' ' + m['signature'] + '` | `' + call + '` |')
        ui += ['', '## Complete application class list', ''] + ['- `' + c + '`' for c in classes if c.startswith('com.apple.xsr.')]
        ui += ['', '## English resource keys', '', 'Values and all locale variants remain immutable JAR resources. Keys enumerate labels/messages and do not prove a function is reachable.', '']
        data = z.read('com/apple/xsr/resources/GlobalResources.properties').decode('iso-8859-1')
        keys = sorted(set(line.split('=',1)[0].strip() for line in data.splitlines() if '=' in line and not line.lstrip().startswith('#')))
        ui += ['- `' + k.replace('`','') + '`' for k in keys]
        (out / 'UI-INVENTORY.md').write_text('\n'.join(ui) + '\n')
        groups = [
            ('Apple application and support', ('com/apple/',), '1.5.1 / 1.5.1GMc5', 'Apple proprietary; redistribution unresolved'),
            ('Chaotic support', ('com/chaotic/',), None, 'NOASSERTION'),
            ('BrowserLauncher', ('edu/stanford/ejalbert/',), None, 'NOASSERTION'),
            ('JmDNS', ('javax/jmdns/',), '0.2', 'NOASSERTION'),
            ('Xerces and DOM implementations', ('org/apache/xerces/', 'org/apache/html/', 'org/apache/wml/'), '2.0.0 (Xerces)', 'NOASSERTION'),
            ('Xalan and XML/XPath support', ('org/apache/xalan/', 'org/apache/xml/', 'org/apache/xpath/'), '2.3.0 (Xalan)', 'NOASSERTION'),
            ('Log4j', ('org/apache/log4j/',), '1.x; exact version unresolved', 'NOASSERTION'),
            ('BCEL', ('org/apache/bcel/',), None, 'Apache-1.1; BCEL.LICENSE.txt'),
            ('Regexp', ('org/apache/regexp/',), None, 'Apache-1.1; regexp.LICENSE.txt'),
            ('JLex', ('JLex/',), None, 'custom notice; JLex.LICENSE.txt'),
            ('Java CUP', ('java_cup/',), '0.10j', 'custom notice; java_cup.LICENSE.txt, runtime.LICENSE.txt'),
            ('XML API classes', ('javax/xml/', 'org/w3c/', 'org/xml/'), None, 'NOASSERTION'),
        ]
        components=[]
        for name,prefixes,version,license_name in groups:
            files={n:h for n,h in hashes.items() if n.startswith(prefixes)}
            components.append({'name':name,'version':version,'license_evidence':license_name,'files':files,'component_tree_sha256':tree_hash(files)})
        known={n for c in components for n in c['files']}
        components.append({'name':'Other resources and notices','version':None,'license_evidence':'NOASSERTION','files':{n:h for n,h in hashes.items() if n not in known}})
        sbom={'format':'project inventory schema 1 (not asserted SPDX/CycloneDX conformant)','scope':'vendored JAR entries; build JDK separately in jdk-lock.json; no bundled runtime','hash_definition':'component hash = SHA256 canonical JSON relative entry to SHA256; not upstream distribution checksum','jar_sha256':result['jar_sha256'],'components':components}
        (out / 'sbom.json').write_text(json.dumps(sbom,indent=2)+'\n')
        print(json.dumps({'classes':len(classes),'methods':len(methods),'factory_overloads':len(factory),'ui_resource_keys':len(keys),'jar_entries':len(hashes)}))


if __name__ == '__main__': main()
